/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as AuthCallbackRouteImport } from './routes/auth_/callback'
import { Route as ProtectedSharedRouteRouteImport } from './routes/_protected/shared/route'
import { Route as ProtectedSearchRouteRouteImport } from './routes/_protected/search/route'
import { Route as ProtectedListsIndexRouteImport } from './routes/_protected/lists/index'
import { Route as ProtectedListsIdRouteImport } from './routes/_protected/lists/$id'
import { Route as ProtectedListsIdJoinRouteImport } from './routes/_protected/lists/$id.join'
import { Route as ProtectedDetailsTypeIdRouteImport } from './routes/_protected/details/$type/$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSharedRouteRoute = ProtectedSharedRouteRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSearchRouteRoute = ProtectedSearchRouteRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedListsIndexRoute = ProtectedListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedListsIdRoute = ProtectedListsIdRouteImport.update({
  id: '/lists/$id',
  path: '/lists/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedListsIdJoinRoute = ProtectedListsIdJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ProtectedListsIdRoute,
} as any)
const ProtectedDetailsTypeIdRoute = ProtectedDetailsTypeIdRouteImport.update({
  id: '/details/$type/$id',
  path: '/details/$type/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/auth': typeof AuthRouteRoute
  '/search': typeof ProtectedSearchRouteRoute
  '/shared': typeof ProtectedSharedRouteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/lists/$id': typeof ProtectedListsIdRouteWithChildren
  '/lists/': typeof ProtectedListsIndexRoute
  '/details/$type/$id': typeof ProtectedDetailsTypeIdRoute
  '/lists/$id/join': typeof ProtectedListsIdJoinRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRoute
  '/search': typeof ProtectedSearchRouteRoute
  '/shared': typeof ProtectedSharedRouteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof ProtectedIndexRoute
  '/lists/$id': typeof ProtectedListsIdRouteWithChildren
  '/lists': typeof ProtectedListsIndexRoute
  '/details/$type/$id': typeof ProtectedDetailsTypeIdRoute
  '/lists/$id/join': typeof ProtectedListsIdJoinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRoute
  '/_protected/search': typeof ProtectedSearchRouteRoute
  '/_protected/shared': typeof ProtectedSharedRouteRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/lists/$id': typeof ProtectedListsIdRouteWithChildren
  '/_protected/lists/': typeof ProtectedListsIndexRoute
  '/_protected/details/$type/$id': typeof ProtectedDetailsTypeIdRoute
  '/_protected/lists/$id/join': typeof ProtectedListsIdJoinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/shared'
    | '/auth/callback'
    | '/lists/$id'
    | '/lists/'
    | '/details/$type/$id'
    | '/lists/$id/join'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/search'
    | '/shared'
    | '/auth/callback'
    | '/'
    | '/lists/$id'
    | '/lists'
    | '/details/$type/$id'
    | '/lists/$id/join'
  id:
    | '__root__'
    | '/_protected'
    | '/auth'
    | '/_protected/search'
    | '/_protected/shared'
    | '/auth_/callback'
    | '/_protected/'
    | '/_protected/lists/$id'
    | '/_protected/lists/'
    | '/_protected/details/$type/$id'
    | '/_protected/lists/$id/join'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/shared': {
      id: '/_protected/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof ProtectedSharedRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/search': {
      id: '/_protected/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ProtectedSearchRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/lists/': {
      id: '/_protected/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof ProtectedListsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/lists/$id': {
      id: '/_protected/lists/$id'
      path: '/lists/$id'
      fullPath: '/lists/$id'
      preLoaderRoute: typeof ProtectedListsIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/lists/$id/join': {
      id: '/_protected/lists/$id/join'
      path: '/join'
      fullPath: '/lists/$id/join'
      preLoaderRoute: typeof ProtectedListsIdJoinRouteImport
      parentRoute: typeof ProtectedListsIdRoute
    }
    '/_protected/details/$type/$id': {
      id: '/_protected/details/$type/$id'
      path: '/details/$type/$id'
      fullPath: '/details/$type/$id'
      preLoaderRoute: typeof ProtectedDetailsTypeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedListsIdRouteChildren {
  ProtectedListsIdJoinRoute: typeof ProtectedListsIdJoinRoute
}

const ProtectedListsIdRouteChildren: ProtectedListsIdRouteChildren = {
  ProtectedListsIdJoinRoute: ProtectedListsIdJoinRoute,
}

const ProtectedListsIdRouteWithChildren =
  ProtectedListsIdRoute._addFileChildren(ProtectedListsIdRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedSearchRouteRoute: typeof ProtectedSearchRouteRoute
  ProtectedSharedRouteRoute: typeof ProtectedSharedRouteRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedListsIdRoute: typeof ProtectedListsIdRouteWithChildren
  ProtectedListsIndexRoute: typeof ProtectedListsIndexRoute
  ProtectedDetailsTypeIdRoute: typeof ProtectedDetailsTypeIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedSearchRouteRoute: ProtectedSearchRouteRoute,
  ProtectedSharedRouteRoute: ProtectedSharedRouteRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedListsIdRoute: ProtectedListsIdRouteWithChildren,
  ProtectedListsIndexRoute: ProtectedListsIndexRoute,
  ProtectedDetailsTypeIdRoute: ProtectedDetailsTypeIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
